### PR TITLE
Fix modifications after Commit #23 for the French translation

### PR DESCRIPTION
**Pull request by richoux**
I also changed/translated some new parts added after Commit #23.

### CODE REVIEW

**Review by theyokohamalife — CHANGES_REQUESTED** [review]
Thank you! Some new French translations were just added before this one. Could you check and resolve the conflicts?

**Comment by richoux** [comment]
I already did actually: I did a pull this afternoon just before making my modifications.

**Comment by ann-kilzer** [comment]
We are seeing a merge conflict. Please edit directly via "Resolve conflicts."

This guide may help: https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Review by ann-kilzer — APPROVED** [review]
LGTM 🧜🏻

**Review by theyokohamalife — APPROVED** [review]
Thank you!!

**Pull request merged**
