### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by jcrevits**
I noticed some keys that were missing and some translations that were not up to date anymore. Leveraged (and modified) Deepl's amazing machine translations to make my life easier.

I'm also not up to speed re: inclusive writing in French. I wanted to change all **é** (and equivalent) to **é(e)** but I'm not sure if that is considered "correct" 🤔

### CODE REVIEW

**Comment by jcrevits** [comment]
Ah, maybe I was not supposed to bring in the missing keys and it's probably done by code before being translated?

That would make sense. Consider French as being ahead of the curve maybe? 😛

**Comment by ann-kilzer** [comment]
Are you fluent in French? We have had several rounds of translation and are moving away from machine translation.

**Comment by jcrevits** [comment]
I think LaShawn can vouch for me 😁 (we work together, hi LaShawn 👋 )

I was also a professional EN>FR translator in another life and yes, I am a French speaker! This is me - https://www.linkedin.com/in/jcrevits

Deepl is _that_ good though and is used by professional translators for PEMT (post-editing machine translation). If you want to make localization easier/faster, I'd recommend it 🙂

**Review by ann-kilzer — APPROVED** [review]
LGTM 🥇 


Thanks! 

Pardon my caution, I have had dubious quality submissions in the past and just wanted to ensure you could verify the language. And thanks for the note about DeepL!

Merci!

**Pull request merged**
