### PR TITLE
Update french translation

### PR DESCRIPTION
**Pull request by JohnTitor2036**
I've added missing translation.
I assume that "Find a Doc, JAPAN" should not be translated because it's the name of the website, but if you do want it translated, it would be : "Trouver un médecin, JAPON" :)

### CODE REVIEW

**Review by ann-kilzer — APPROVED** [review]
LGTM 🇫🇷 

Thank you!!!

Yes, for now let's leave the title in English.

**Comment by ann-kilzer** [comment]
I am waiting for the linter to check the files, then I will merge this in 🍡

**Comment by theyokohamalife** [comment]
Thank you for the updated translation!! We just need to figure out what needs to be changed so that it passes the checks and can be merged. It might be something on our end. @ann-kilzer thoughts?

**Comment by JohnTitor2036** [comment]
Hmmmm. I've edit the file directly in the GitHub interface and didn't touch the indentation. Maybe it's an error with the last line of the file, it seems to have been automatically modify by GitHub. It probably switch between CR (\r) and CRLF (\r\n). If it's not fixed when I finish working, I'll try to change it back on my computer ^^

**Comment by ann-kilzer** [comment]
Lol it's the bot I set up to say "ようこそ”, apparently it failed 🤖 Pardon our mess

Eslint is good so I will merge.

**Pull request merged**
