### PR TITLE
Fix typo in key for new leads strings

### PR DESCRIPTION
**Pull request by renderf0x**
Sorry, 'contributors' was misspelled in one of the keys here. It's usable as is but I'd rather fix it asap.

### CODE REVIEW

**Review by ann-kilzer — APPROVED** [review]

**Comment by ann-kilzer** [comment]
Ahh thanks for getting this, but can you please fix the merge conflict and then update the Japanese appropriately? Thanks!

**Review by ann-kilzer — CHANGES_REQUESTED** [review]
see prior comment

**Comment by renderf0x** [comment]
> Ahh thanks for getting this, but can you please fix the merge conflict and then update the Japanese appropriately? Thanks!

Haha LaShawn got at the new string too fast =)

**Comment by renderf0x** [comment]
> see prior comment

kk. should be good to go once you approve.

**Comment by renderf0x** [comment]
Off to bed now but feel free to merge this in if we want it.

**Review by ann-kilzer — APPROVED** [review]
LGTM 👥

**Pull request merged**
