### PR TITLE
Add language name and direction where relevant as meta keys in the localization file.

### PR DESCRIPTION
**Pull request by renderf0x**
Useful for future automation, such as automatically populating localization frameworks.

### CODE REVIEW

**Review by ann-kilzer — CHANGES_REQUESTED** [review]
While I love that we're automating the locale selector updates, I'd rather not have "special keys" in this file for a couple of reasons.

1) I've never seen such a practice in i18n files (please correct me if you have more info)
2) Most of the translators are non-technical and may be confused by this
3) It complicates the tooling I am building for key propagation in #33 

Instead, let's have an auxiliary file of [ISO 639-1 data](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). It could be tuples of `code`, `name`, `dir`

Then we could:

1. Detect all files present within the `locales` folder and extract the codes
2. Match the codes to the names and directions from the auxiliary file
3. Build the JSON for the locale selector.

What do you think?

**Comment by renderf0x** [comment]
> While I love that we're automating the locale selector updates, I'd rather not have "special keys" in this file for a couple of reasons:
> 
> 1. I've never seen such a practice in i18n files (please correct me if you have more info)
> 2. Most of the translators are non-technical and may be confused by this
> 3. It complicates the tooling I am building for key propagation in #33
> 
> Instead, let's have an auxiliary file of [ISO 639-1 data](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). It could be tuples of `code`, `name`, `dir`
> 
> Then we could:
> 
> 1. Detect all files present within the `locales` folder and extract the codes
> 2. Match the codes to the names and directions from the auxiliary file
> 3. Build the JSON for the locale selector.
> 
> What do you think?

Yeah, that's totally fine with me @ann-kilzer . In fact, that was another way I was considering doing this in the frontend PR.
If we're going to go this route, it might even be a great opportunity to simplify, and skip automated interpolation.

Here's what I propose:

We create a `supported_languages` file in this repo (since it is the i18n source), and fill with with code/canonical name/dir for each of the languages we have currently (not all existing entries). There's a small one-time chore necessary to add the ISO data when we create new translation files, but since it's easily accessible, and infrequent, I think we can just make it part of the process of adding a language.

This then makes the automation on the front end side trivial, since we're just reading a single file.
Less acrobatics are usually better for maintainability.

Thoughts?

If you're good with that then I'll close this out and make a new PR for that languages file here.

**Comment by ann-kilzer** [comment]
Yes if you'd like to make a supported_languages in the top level directory, that's good. Though writing a scraper and getting all the ISO 639-1 pairs is something I could help with too, we could always save that for step 2.

**Comment by renderf0x** [comment]
Rad. Thanks @ann-kilzer . I'll close this out and prep a file with supported langs. Let's discuss about scraping offline.

**Pull request closed without merging**
