### PR TITLE
adding arabic for experimentation

### PR DESCRIPTION
**Pull request by TrajM**
Not sure if the character encoding and right-to-left writing work correctly. It is worth trying

### CODE REVIEW

**Comment by ann-kilzer** [comment]
Thank you!!

We can do it but may need to configure the `dir: rtl` setting in the nuxt config @theyokohamalife

**Review by ann-kilzer — APPROVED** [review]
Looking good. We may ask for your help again when mixing English and Arabic so we don't get

adoyoT nwahSaL   

I am not sure the proper way to combine the two 😅

**Comment by TrajM** [comment]
Haha, yeah I wanted to check because it was also weird when I wrote the json file. Mixing arabic and english in the same sentence works fine on Word but depending on the web environment it might reverse the letters

**Review by theyokohamalife — APPROVED** [review]
Thank you!! I'll test this out tonight!

**Pull request merged**
